---
- hosts:
    directory
    ftp
    queue
    database
    consumer
    web
  roles:
  - role: common

- hosts:
    consumer
  roles:
  - role: consumer

- hosts:
    database
  roles:
  - role: database

- hosts:
    directory
  roles:
  - role: directory

- hosts:
    ftp
  roles:
  - role: ftp

- hosts:
    queue
  roles:
  - role: queue

- hosts:
    web
  roles:
  - role: web
